# Generated by Django 5.0.4 on 2024-05-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_perfilusuario_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='peliculas_manual',
            field=models.ManyToManyField(blank=True, related_name='agregadas_manualmente', to='api.pelicula'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='series_manual',
            field=models.ManyToManyField(blank=True, related_name='agregadas_manualmente', to='api.serie'),
        ),
    ]
