# Generated by Django 5.0.4 on 2024-05-05 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_media_movie_series_userprofile_avatar_watchedmedia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchedmedia',
            name='media',
        ),
        migrations.AddField(
            model_name='watchedmedia',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.movie'),
        ),
        migrations.AddField(
            model_name='watchedmedia',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.series'),
        ),
        migrations.DeleteModel(
            name='Media',
        ),
    ]
