# Generated by Django 5.0.4 on 2024-05-05 19:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_watchedmedia_media_watchedmedia_movie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2024, 5, 5, 19, 18, 2, 8949, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
