# Generated by Django 5.0.4 on 2024-05-07 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_perfilusuario_peliculas_manual_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='series_vistas',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='peliculas_vistas',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='peliculas_manual',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='series_manual',
        ),
        migrations.DeleteModel(
            name='MediaVista',
        ),
    ]
