# Generated by Django 5.0.4 on 2024-05-05 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_series_release_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='release_date',
        ),
    ]
