# Generated by Django 5.0.4 on 2024-05-05 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_series_release_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Series',
            new_name='Serie',
        ),
    ]
